# Generated by Django 6.0.1 on 2026-05-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_contratbail_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_concerne', models.DateField(verbose_name='Mois concerné')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=30, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('en_retard', 'En retard')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='properties.contratbail')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-mois_concerne'],
            },
        ),
    ]
