# Generated by Django 6.0.1 on 2026-05-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profillocataire',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locataires', to='accounts.profilproprietaire', verbose_name='Propriétaire'),
        ),
    ]
