# Generated by Django 6.0.5 on 2026-05-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('studio', 'Studio'), ('maison', 'Maison')], max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(default='Lomé', max_length=100)),
                ('superficie', models.PositiveIntegerField(help_text='Superficie en m²')),
                ('loyer_mensuel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('caution', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='biens/')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('loue', 'Loué'), ('en_travaux', 'En travaux')], default='libre', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='accounts.profilproprietaire')),
            ],
            options={
                'verbose_name': 'Bien immobilier',
                'verbose_name_plural': 'Biens immobiliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratBail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_loyer', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_caution', models.DecimalField(decimal_places=0, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resilie', 'Résilié'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='properties.bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='accounts.profillocataire')),
            ],
            options={
                'verbose_name': 'Contrat de bail',
                'verbose_name_plural': 'Contrats de bail',
                'ordering': ['-created_at'],
            },
        ),
    ]
