# Generated by Django 6.0.1 on 2026-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratbail',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
